# TEST PROGRAM FOR THE EMULATOR, TOKENIZES A STRING AND PRINTS OUT THE TOKEN.
# NOTE IF IT IS NOT OBVIOUS ALREADY, I DID NOT WRITE THIS ASSEMBLY, IT WAS GENERATED BY AN LLM.
# I WAS GOING TO WRITE IT IN C MYSELF, BUT REALIZED I COULDNT COMPILE IT FROM C OR C++ EITHER, COS OF SYSCALL COMPATIBILITY.
# BETWEEN MY SYSTEM AND THE EMULATOR. SORRE.
.text
.set noreorder
.globl _start

_start:
    # Jump to main code
    addiu $t0, $zero, main_start
    jr $t0
    nop

# Embedded data section
input_str_data:
    .ascii "The morning coffee holds power"
    .byte 0
    .align 2

token_msg_data:
    .ascii "Token: "
    .byte 0
    .align 2

newline_data:
    .ascii "\n"
    .byte 0
    .align 2

# Token buffer - 64 bytes
token_buffer_data:
    .space 64
    .align 2

main_start:
    # Initialize pointers - calculate addresses relative to known positions
    addiu $s0, $zero, 12        # Input string starts at offset 12 from _start
    addiu $s1, $zero, 80        # Token buffer starts around offset 80
    addiu $s2, $s1, 0           # Save original buffer start position
    
    # Initialize constants
    addiu $s3, $zero, 32        # Space character
    addiu $s4, $zero, 0         # Null terminator
    addiu $s5, $zero, 44        # Token message at offset 44
    addiu $s6, $zero, 68        # Newline at offset 68

tokenize_loop:
    # Load current character
    lb $t0, 0($s0)
    
    # Check for end of string
    beq $t0, $s4, handle_final_token
    nop
    
    # Check if character is space
    beq $t0, $s3, handle_token_end
    nop
    
    # Add character to token buffer
    sb $t0, 0($s1)
    addiu $s1, $s1, 1           # Advance buffer pointer
    addiu $s0, $s0, 1           # Advance input pointer
    
    # Continue loop
    addiu $t1, $zero, tokenize_loop
    jr $t1
    nop

handle_token_end:
    # Check if we have a token (buffer moved from start)
    beq $s1, $s2, skip_empty
    nop
    
    # Print the token
    addiu $t2, $zero, print_current_token
    jr $t2
    nop

return_from_print:
    # Reset buffer pointer
    addu $s1, $s2, $zero
    
skip_empty:
    # Move to next character in input
    addiu $s0, $s0, 1
    
    # Continue main loop
    addiu $t1, $zero, tokenize_loop
    jr $t1
    nop

handle_final_token:
    # Check if we have a final token
    beq $s1, $s2, program_exit
    nop
    
    # Print final token
    addiu $t2, $zero, print_current_token
    jr $t2
    nop

final_exit:
    # Exit program
    addiu $v0, $zero, 0         # Exit syscall
    syscall

program_exit:
    addiu $t1, $zero, final_exit
    jr $t1
    nop

print_current_token:
    # Null terminate current token
    sb $s4, 0($s1)
    
    # Print "Token: " message
    addiu $v0, $zero, 4         # Write syscall
    addiu $a0, $zero, 2         # Write mode
    addu $a1, $s5, $zero        # Message address
    syscall
    
    # Print the actual token
    addiu $v0, $zero, 4         # Write syscall
    addiu $a0, $zero, 2         # Write mode  
    addu $a1, $s2, $zero        # Token buffer address
    syscall
    
    # Print newline
    addiu $v0, $zero, 4         # Write syscall
    addiu $a0, $zero, 2         # Write mode
    addu $a1, $s6, $zero        # Newline address
    syscall
    
    # Determine return address
    lb $t0, 0($s0)              # Check current input character
    beq $t0, $s4, final_exit    # If null, go to final exit
    nop
    
    # Otherwise return to main processing
    addiu $t1, $zero, return_from_print
    jr $t1
    nop
